image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy

setup:
  stage: build
  script: npm i -g pnpm && pnpm install

test:
  stage: test
  script: pnpm run test:unit
  coverage: '/^Statements\s*:\s*([^%]+)/'

pages:
  stage: deploy
  script:
  - pnpm install
  - pnpm run build
  artifacts:
    paths:
    - dist
  only:
  - dev
