pull_request_rules:
  - name: Renovate updates
    conditions:
      - author=renovate[bot]
      - status-success=deploy
    actions:
      merge:
        method: squash
  - name: Approved PRs
    conditions:
      - approved-reviews-by=binhonglee
      - status-success=deploy
    actions:
      merge:
        method: squash