language: node_js
os:
  - linux
  - osx

node_js:
  - "node"
  - "stable"

install:
  - npm install
  - npm install -g codecov

script:
  - npm test
  - codecov -t $CODECOV_TOKEN
  - npm build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: dist
  on:
    branch: master
