language: node_js
os:
  - linux
  - osx

node_js:
  - "node"
  - "stable"

install:
  - pnpm install
  - pnpm install -g codecov

script:
  - pnpm run test:unit
  - codecov -t $CODECOV_TOKEN
  - pnpm run build
  - cp -r images dist

deploy:
  edge: true
  cleanup: false
  strategy: git
  provider: pages
  github-token: $GITHUB_TOKEN
  target-branch: dist
  local-dir: dist
  keep_history: true
  on:
    branch: dev
    condition:
      - "$(uname -s) = Darwin"
      - "$BRANCH = stable"